version: '3.8'

services:
  back:
    build: ./backend
    command: python3 -m flask run --host=0.0.0.0
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=./src/main.py
      - DATABASE_URL=postgresql://postgres:password@db:5432/gamehub
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gamehub
  front:
    build: ./frontend/videogames-front
    ports:
      - 80:80

volumes:
  postgres_data: